import Dexie, { type Table } from "dexie";
import type {
  SHG,
  Member,
  Transaction,
  Meeting,
  TrustPassport,
  ReportItem,
  SyncQueueItem,
} from "@/types";

export class SakhiSetuDatabase extends Dexie {
  shgs!: Table<SHG, string>;
  members!: Table<Member, string>;
  transactions!: Table<Transaction, string>;
  meetings!: Table<Meeting, string>;
  trustPassports!: Table<TrustPassport, string>;
  reports!: Table<ReportItem, string>;
  syncQueue!: Table<SyncQueueItem, string>;

  constructor() {
    super("SakhiSetuDB");
    this.version(1).stores({
      shgs: "id",
      members: "id, shgId, name, status",
      transactions: "id, memberId, timestamp, synced",
      meetings: "id, shgId, meetingDate",
      trustPassports: "shgId",
      reports: "id, shgId, status",
      syncQueue: "id, collection, timestamp",
    });
  }
}

export const dbLocal = new SakhiSetuDatabase();

// Initial Seed Data for 15 realistic women members in Kondhapuri, Pune
export const initialSHG: SHG = {
  id: "shg_001",
  name: "Sakhi Mahila Bachat Gat",
  village: "Kondhapuri",
  district: "Pune",
  state: "Maharashtra",
  leader: "Sunita Pawar",
  formed: "March 2019",
  cycle: "Cycle 7 · Week 3",
  passportId: "SS-MH-2019-04871",
  createdDate: "2019-03-15",
  membersCount: 15,
  corpus: 148500,
  trustScore: 768,
};

export const initialMembers: Member[] = [
  {
    id: "m1",
    shgId: "shg_001",
    name: "Sunita Pawar",
    initials: "SP",
    role: "President",
    savings: 14200,
    loan: 20000,
    loanPaid: 16500,
    attendance: 100,
    streak: 24,
    status: "current",
    contributions: [
      { label: "Nov", amount: 600 },
      { label: "Oct", amount: 600 },
      { label: "Sep", amount: 500 },
      { label: "Aug", amount: 600 },
    ],
  },
  {
    id: "m2",
    shgId: "shg_001",
    name: "Kavita Jadhav",
    initials: "KJ",
    role: "Treasurer",
    savings: 12850,
    loan: 15000,
    loanPaid: 9000,
    attendance: 96,
    streak: 18,
    status: "current",
    contributions: [
      { label: "Nov", amount: 500 },
      { label: "Oct", amount: 500 },
      { label: "Sep", amount: 500 },
      { label: "Aug", amount: 400 },
    ],
  },
  {
    id: "m3",
    shgId: "shg_001",
    name: "Rekha Shinde",
    initials: "RS",
    role: "Secretary",
    savings: 11100,
    loan: 0,
    loanPaid: 0,
    attendance: 92,
    streak: 12,
    status: "cleared",
    contributions: [
      { label: "Nov", amount: 500 },
      { label: "Oct", amount: 450 },
      { label: "Sep", amount: 500 },
      { label: "Aug", amount: 500 },
    ],
  },
  {
    id: "m4",
    shgId: "shg_001",
    name: "Mangala Bhosale",
    initials: "MB",
    role: "Member",
    savings: 9400,
    loan: 12000,
    loanPaid: 4200,
    attendance: 78,
    streak: 4,
    status: "watch",
    contributions: [
      { label: "Nov", amount: 300 },
      { label: "Oct", amount: 0 },
      { label: "Sep", amount: 400 },
      { label: "Aug", amount: 400 },
    ],
  },
  {
    id: "m5",
    shgId: "shg_001",
    name: "Asha Kamble",
    initials: "AK",
    role: "Member",
    savings: 10250,
    loan: 8000,
    loanPaid: 6400,
    attendance: 94,
    streak: 15,
    status: "current",
    contributions: [
      { label: "Nov", amount: 450 },
      { label: "Oct", amount: 450 },
      { label: "Sep", amount: 450 },
      { label: "Aug", amount: 400 },
    ],
  },
  {
    id: "m6",
    shgId: "shg_001",
    name: "Vaishali More",
    initials: "VM",
    role: "Member",
    savings: 8720,
    loan: 10000,
    loanPaid: 8500,
    attendance: 88,
    streak: 9,
    status: "current",
    contributions: [
      { label: "Nov", amount: 400 },
      { label: "Oct", amount: 400 },
      { label: "Sep", amount: 350 },
      { label: "Aug", amount: 400 },
    ],
  },
  {
    id: "m7",
    shgId: "shg_001",
    name: "Shobha Gaikwad",
    initials: "SG",
    role: "Member",
    savings: 13300,
    loan: 18000,
    loanPaid: 15300,
    attendance: 98,
    streak: 21,
    status: "current",
    contributions: [
      { label: "Nov", amount: 550 },
      { label: "Oct", amount: 550 },
      { label: "Sep", amount: 550 },
      { label: "Aug", amount: 500 },
    ],
  },
  {
    id: "m8",
    shgId: "shg_001",
    name: "Nanda Chavan",
    initials: "NC",
    role: "Member",
    savings: 7650,
    loan: 0,
    loanPaid: 0,
    attendance: 84,
    streak: 6,
    status: "cleared",
    contributions: [
      { label: "Nov", amount: 350 },
      { label: "Oct", amount: 350 },
      { label: "Sep", amount: 300 },
      { label: "Aug", amount: 350 },
    ],
  },
  {
    id: "m9",
    shgId: "shg_001",
    name: "Lata Deshmukh",
    initials: "LD",
    role: "Member",
    savings: 9100,
    loan: 10000,
    loanPaid: 3000,
    attendance: 90,
    streak: 10,
    status: "current",
    contributions: [
      { label: "Nov", amount: 400 },
      { label: "Oct", amount: 400 },
      { label: "Sep", amount: 400 },
      { label: "Aug", amount: 400 },
    ],
  },
  {
    id: "m10",
    shgId: "shg_001",
    name: "Sangeeta Mane",
    initials: "SM",
    role: "Member",
    savings: 8200,
    loan: 0,
    loanPaid: 0,
    attendance: 86,
    streak: 8,
    status: "cleared",
    contributions: [
      { label: "Nov", amount: 350 },
      { label: "Oct", amount: 350 },
      { label: "Sep", amount: 350 },
      { label: "Aug", amount: 350 },
    ],
  },
  {
    id: "m11",
    shgId: "shg_001",
    name: "Pooja Salunkhe",
    initials: "PS",
    role: "Member",
    savings: 9800,
    loan: 0,
    loanPaid: 0,
    attendance: 95,
    streak: 14,
    status: "cleared",
    contributions: [
      { label: "Nov", amount: 500 },
      { label: "Oct", amount: 450 },
      { label: "Sep", amount: 500 },
      { label: "Aug", amount: 450 },
    ],
  },
  {
    id: "m12",
    shgId: "shg_001",
    name: "Sarita Kadam",
    initials: "SK",
    role: "Member",
    savings: 11500,
    loan: 15000,
    loanPaid: 12000,
    attendance: 92,
    streak: 11,
    status: "current",
    contributions: [
      { label: "Nov", amount: 500 },
      { label: "Oct", amount: 500 },
      { label: "Sep", amount: 500 },
      { label: "Aug", amount: 500 },
    ],
  },
  {
    id: "m13",
    shgId: "shg_001",
    name: "Usha Thorat",
    initials: "UT",
    role: "Member",
    savings: 6900,
    loan: 5000,
    loanPaid: 1500,
    attendance: 80,
    streak: 5,
    status: "watch",
    contributions: [
      { label: "Nov", amount: 300 },
      { label: "Oct", amount: 250 },
      { label: "Sep", amount: 300 },
      { label: "Aug", amount: 300 },
    ],
  },
  {
    id: "m14",
    shgId: "shg_001",
    name: "Archana Jagtap",
    initials: "AJ",
    role: "Member",
    savings: 10400,
    loan: 0,
    loanPaid: 0,
    attendance: 98,
    streak: 19,
    status: "cleared",
    contributions: [
      { label: "Nov", amount: 500 },
      { label: "Oct", amount: 500 },
      { label: "Sep", amount: 500 },
      { label: "Aug", amount: 450 },
    ],
  },
  {
    id: "m15",
    shgId: "shg_001",
    name: "Anita Wagh",
    initials: "AW",
    role: "Member",
    savings: 12100,
    loan: 0,
    loanPaid: 0,
    attendance: 96,
    streak: 17,
    status: "cleared",
    contributions: [
      { label: "Nov", amount: 550 },
      { label: "Oct", amount: 500 },
      { label: "Sep", amount: 500 },
      { label: "Aug", amount: 550 },
    ],
  },
];

export const initialReports: ReportItem[] = [
  {
    id: "r1",
    shgId: "shg_001",
    title: "Bank Dossier · Nov 2026",
    kind: "Full dossier",
    pages: 14,
    generated: "12 Nov 2026",
    size: "1.8 MB",
    status: "Verified",
    qrId: "SS-MH-2019-04871",
    hash: "a4f8e21c9b3d7e5f102938475610293847561029384756102938475610293847",
  },
  {
    id: "r2",
    shgId: "shg_001",
    title: "Loan Utilisation Report",
    kind: "Loan annexure",
    pages: 6,
    generated: "04 Nov 2026",
    size: "740 KB",
    status: "Shared",
    qrId: "SS-MH-2019-04871-loan",
    hash: "b9c8d7e6f5a43210987654321098765432109876543210987654321098765432",
  },
  {
    id: "r3",
    shgId: "shg_001",
    title: "Quarterly Audit Pack Q3",
    kind: "Audit",
    pages: 22,
    generated: "28 Oct 2026",
    size: "3.1 MB",
    status: "Verified",
    qrId: "SS-MH-2019-04871-q3",
    hash: "c1d2e3f4a5b67890123456789012345678901234567890123456789012345678",
  },
  {
    id: "r4",
    shgId: "shg_001",
    title: "Attendance & Governance Sheet",
    kind: "Compliance",
    pages: 4,
    generated: "19 Oct 2026",
    size: "410 KB",
    status: "Draft",
    qrId: "SS-MH-2019-04871-gov",
    hash: "d9e8f7a6b5c43210987654321098765432109876543210987654321098765432",
  },
];

export async function seedDatabase() {
  const shgCount = await dbLocal.shgs.count();
  if (shgCount === 0) {
    await dbLocal.shgs.put(initialSHG);
    await dbLocal.members.bulkPut(initialMembers);
    await dbLocal.reports.bulkPut(initialReports);
    
    // Initial Trust Passport
    await dbLocal.trustPassports.put({
      shgId: "shg_001",
      score: 768,
      grade: "Grade A · Bank-ready",
      generatedDate: "2026-11-12",
      breakdown: [
        { label: "Repayment discipline", weight: 35, score: 94, note: "99% instalments paid on time" },
        { label: "Savings regularity", weight: 25, score: 88, note: "31 of 34 weekly cycles fully collected" },
        { label: "Meeting attendance", weight: 20, score: 91, note: "Average 91% across last 12 meetings" },
        { label: "Contribution frequency", weight: 20, score: 82, note: "All 15 members actively contributing" },
      ],
      timeline: [
        { period: "Jun", score: 612 },
        { period: "Jul", score: 648 },
        { period: "Aug", score: 685 },
        { period: "Sep", score: 712 },
        { period: "Oct", score: 742 },
        { period: "Nov", score: 768 },
      ],
    });
  }
}
