/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeetingRouteImport } from './routes/meeting'
import { Route as MembersRouteImport } from './routes/members'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as TrustPassportRouteImport } from './routes/trust-passport'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as VerifyReportIdRouteImport } from './routes/verify.$reportId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingRoute = MeetingRouteImport.update({
  id: '/meeting',
  path: '/meeting',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustPassportRoute = TrustPassportRouteImport.update({
  id: '/trust-passport',
  path: '/trust-passport',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyReportIdRoute = VerifyReportIdRouteImport.update({
  id: '/$reportId',
  path: '/$reportId',
  getParentRoute: () => VerifyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/meeting': typeof MeetingRoute
  '/members': typeof MembersRoute
  '/reports': typeof ReportsRoute
  '/trust-passport': typeof TrustPassportRoute
  '/verify': typeof VerifyRouteWithChildren
  '/verify/$reportId': typeof VerifyReportIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/meeting': typeof MeetingRoute
  '/members': typeof MembersRoute
  '/reports': typeof ReportsRoute
  '/trust-passport': typeof TrustPassportRoute
  '/verify': typeof VerifyRouteWithChildren
  '/verify/$reportId': typeof VerifyReportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/meeting': typeof MeetingRoute
  '/members': typeof MembersRoute
  '/reports': typeof ReportsRoute
  '/trust-passport': typeof TrustPassportRoute
  '/verify': typeof VerifyRouteWithChildren
  '/verify/$reportId': typeof VerifyReportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/meeting'
    | '/members'
    | '/reports'
    | '/trust-passport'
    | '/verify'
    | '/verify/$reportId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/meeting'
    | '/members'
    | '/reports'
    | '/trust-passport'
    | '/verify'
    | '/verify/$reportId'
  id:
    | '__root__'
    | '/'
    | '/meeting'
    | '/members'
    | '/reports'
    | '/trust-passport'
    | '/verify'
    | '/verify/$reportId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MeetingRoute: typeof MeetingRoute
  MembersRoute: typeof MembersRoute
  ReportsRoute: typeof ReportsRoute
  TrustPassportRoute: typeof TrustPassportRoute
  VerifyRoute: typeof VerifyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting': {
      id: '/meeting'
      path: '/meeting'
      fullPath: '/meeting'
      preLoaderRoute: typeof MeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust-passport': {
      id: '/trust-passport'
      path: '/trust-passport'
      fullPath: '/trust-passport'
      preLoaderRoute: typeof TrustPassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$reportId': {
      id: '/verify/$reportId'
      path: '/$reportId'
      fullPath: '/verify/$reportId'
      preLoaderRoute: typeof VerifyReportIdRouteImport
      parentRoute: typeof VerifyRoute
    }
  }
}

interface VerifyRouteChildren {
  VerifyReportIdRoute: typeof VerifyReportIdRoute
}

const VerifyRouteChildren: VerifyRouteChildren = {
  VerifyReportIdRoute: VerifyReportIdRoute,
}

const VerifyRouteWithChildren =
  VerifyRoute._addFileChildren(VerifyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MeetingRoute: MeetingRoute,
  MembersRoute: MembersRoute,
  ReportsRoute: ReportsRoute,
  TrustPassportRoute: TrustPassportRoute,
  VerifyRoute: VerifyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
